version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: anime-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: anime-qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage


  loader:
    build: ./Backend
    container_name: anime-loader
    command: ["python", "load_all.py"]
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      QDRANT_COLLECTION: ${QDRANT_COLLECTION}
      POSTGRES_PORT: 5432
      QDRANT_HOST: ${QDRANT_HOST}
      QDRANT_PORT: 6333
    volumes:
      - ./Backend/data/output.json:/app/output.json
      - ./Backend/anime_model:/app/anime_model

  backend:
    build: ./Backend
    container_name: anime-backend
    ports:
      - "8000:8000"
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME}
      QDRANT_COLLECTION: ${QDRANT_COLLECTION}
      POSTGRES_HOST:  ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./Backend/anime_model:/app/anime_model
      - ./Backend/data/output.json:/app/output.json
    depends_on:
      - postgres
      - qdrant

  frontend:
    build: ./Frontend
    container_name: anime-frontend
    ports:
      - "8501:8501"
    environment:
      API_BASE: ${API_BASE}
    depends_on:
      backend:
        condition: service_started

  pgadmin:
    image: dpage/pgadmin4
    container_name: anime-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  qdrant_storage:
